[project]
name = "currency-utils"
version = "0.1.0"
description = "Utils for scrapping multi-national currency and tax data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "iso3166>=2.1.1",
    "requests>=2.32.5",
    "xmltodict>=1.0.2",
]
