name: Scrap ISO3166 and M49 from UN

on:
  workflow_dispatch:

jobs:
  download-currencies-rank:
    runs-on: ubuntu-latest
    env:
      DATE:
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - run: set -e
      - name: Get current date
        id: date
        run: echo "CURRENT_DATE=$(date)" >> $GITHUB_ENV
      - name: Scrap currencies ranking from Wikipedia
        run: pip install -r ./scrapper/requirements.txt && python ./scrapper/iso3166_from_m49_scrapper.py
      - uses: actions/upload-artifact@v4
        with:
          name: jsons-artefact
          path: |
            ./countries_iso3166_m49.json
      - name: commit generated jsons
        run: |
          git config user.name "GitHub Actions"
          git config user.email "no-reply@github.com"
          git add ./countries_iso3166_m49.json
          git commit -m "ISO3166 (2/3 alpha) and UN M49 - $DATE"
          git push origin main
