name: Update Tax Prices

on:
  workflow_dispatch:

jobs:
  assemble-tax-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
      - run: pip install -r ./scrapper/requirements.txt
      - run: ls -la
      - run: python ./scrapper/scrapper.py
      - run: ls -la
      - uses: actions/upload-artifact@v3
        with:
          name: sales-tax-json-artefact
          path: ./world_sales_tax.json
      - name: commit generated tax json
        run: |
          git config user.name "GitHub Actions"
          git config user.email "no-reply@github.com"
          git add ./world_sales_tax.json
          git commit -m "Updated sales tax"
          git push origin main
