name: Update JSONs

on:
  workflow_dispatch:

jobs:
  assemble-jsons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
      - run: pip install -r ./scrapper/requirements.txt
      - run: ls -la
      - run: python ./scrapper/scrapper.py
      - run: ls -la
      - uses: actions/upload-artifact@v3
        with:
          name: jsons-artefact
          path: |
            ./world_sales_tax.json
            ./iso4217_currency_codes.json
      - name: commit generated jsons
        run: |
          git config user.name "GitHub Actions"
          git config user.email "no-reply@github.com"
          git add ./world_sales_tax.json
          git add ./iso4217_currency_codes.json
          git commit -m "Updated JSONs"
          git push origin main
